### ISSUE TITLE
Change name from MEAN.js/MEAN to SketchOff

### ISSUE THREAD

**Issue by danielyaa5** [SketchOff/SketchOff-Web#1]
Go through configuration files and initialization files and make changes. Does this require its own branch?

**Comment by rxf0** [comment]
I'd like to think of it as an authoring commit, so I don't believe so. Especially since we're still early in dev.

**Comment by rxf0** [comment]
Partially completed in feature_home_page.

**Comment by asg0451** [comment]
mostly done, some placeholder text still but no more MEAN
