### ISSUE TITLE
Home page information box sign up button displayed after logging in

### ISSUE THREAD

**Issue by rxf0** [SketchOff/SketchOff-Web#14]
Need to add authorization check for button on information box of home page, replace with find game button (or other/none) if authorized.

**Comment by danielyaa5** [comment]
Ng-if="authorization.user"

**Comment by rxf0** [comment]
Fixed. Branch feature_home_page:[aa18e8c](https://github.com/SketchOff/SketchOff-Web/commit/aa18e8cb8f7f918f258bf7181ac9c2ec02f03b69)
