### ISSUE TITLE
Add friend request feature

### ISSUE THREAD

**Issue by danielyaa5** [SketchOff/SketchOff-Web#17]
Here's how I'd implement this

1. Add Friend field to User model. Friend field should be array of User objects.

2. Create friend request field for user. Should be an array of friend_request objects.

3. Create friend_request model. Should have date created and a from field that stores a user object

4. Create navbar dropdown for friend requests. Either get requests by setting up a getfriendsrequest getter in api. Or by pulling from authentication.user object

5. Emit a msg to the friend requestee whenever someone sends them a request. The emit will let the requestee no to update there friend requests. 

6. Accept or ignore buttons.

**Comment by rxf0** [comment]
1. Friend, array of ref to User, added to User schema
2. pendingFriendRequests in User schema added
3. friend_request model is being used, Schema of date created and requested by user reference
4. Friend requests are handled on profile page. Notifications are a to-do, but they update live if one is connected via sockets and are on their profile page.
5. Emitting on all friend management events
6. Implemented

55173a9aabbdfcadba994a641acec93b6c73d91a
