### ISSUE TITLE
Can change username

### ISSUE THREAD

**Issue by rxf0** [SketchOff/SketchOff-Web#20]
You can change your username in profile settings. Changing profile name is okay, but it seems having the ability to change your username may not really be necessary. To fix: disable ability to change username?

Thoughts?

**Comment by danielyaa5** [comment]
Ya I agree its kinda weird, don't see how it hurts since I'm assuming it
rechecks to make sure the username is available. But keep this in mind when
programming that a username could change.

**Comment by rxf0** [comment]
Fix: must be admin to change own username implemented in commit 70677ebcb5f660884f40f3e43173be3c61630983.
Can be reimplemented in future after testing inter-module compatibility.
